# Generated by Django 5.0.6 on 2024-10-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
