# Generated by Django 5.0.6 on 2024-10-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_userform_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='phone',
            field=models.IntegerField(max_length=100, null=True, unique=True),
        ),
    ]
