# Generated by Django 5.0.6 on 2024-10-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_userform_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='phone',
            field=models.TextField(max_length=100, null=True, unique=True),
        ),
    ]
