# Generated by Django 5.0.6 on 2024-10-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('testapp', '0005_rename_userform_userforms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForms',
            new_name='UserForm',
        ),
    ]
