# Generated by Django 5.0.6 on 2024-10-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_rename_userforms_userform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='zip',
        ),
        migrations.AddField(
            model_name='userform',
            name='classe',
            field=models.CharField(choices=[('7eme', '7eme'), ('8eme', '8eme'), ('9eme', '9eme'), ('10eme', '10eme'), ('11emesm', '11eme SM'), ('11emese', '11eme SE'), ('11emess', '11eme SS'), ('12emesm', '12eme SM'), ('12emese', '12eme SE'), ('12emess', '12eme SS'), ('tsm', 'TSM'), ('tse', 'TSE'), ('tss', 'TSS')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userform',
            name='phone',
            field=models.TextField(max_length=5, null=True, unique=True),
        ),
    ]
