# Generated by Django 5.0.6 on 2024-10-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_remove_userform_zip_userform_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='phone',
            field=models.IntegerField(max_length=10, null=True, unique=True),
        ),
    ]
