# Generated by Django 5.0.6 on 2024-10-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_userform_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('7eme', '7eme'), ('8eme', '8eme'), ('9eme', '9eme'), ('10eme', '10eme'), ('11emesm', '11eme SM'), ('11emese', '11eme SE'), ('11emess', '11eme SS'), ('12emesm', '12eme SM'), ('12emese', '12eme SE'), ('12emess', '12eme SS'), ('tsm', 'TSM'), ('tse', 'TSE'), ('tss', 'TSS')], default='', max_length=50)),
                ('prof', models.CharField(max_length=50)),
                ('matieres', models.CharField(choices=[('maths', 'Maths'), ('physique', 'physique'), ('chimie', 'Chimie')], max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('date_ajout', models.DateField(auto_now=True)),
                ('cours', models.FileField(upload_to='pdf')),
                ('phone', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
