# Generated by Django 5.0.6 on 2024-10-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur'), ('Directeur', 'Directeur'), ('Professeur', 'Professeur')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userform',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
