# Generated by Django 5.0.6 on 2024-10-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_userform_role_alter_userform_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='date_aj',
            field=models.DateField(auto_now=True),
        ),
    ]
