# Generated by Django 5.0.6 on 2024-10-25 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_userform_date_aj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Administrateur', 'Administrateur'), ('Directeur', 'Directeur'), ('Professeur', 'Professeur')], default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userform',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.role'),
        ),
    ]
