# Generated by Django 5.0.6 on 2024-10-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_classe_alter_userform_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='phone',
            field=models.IntegerField(max_length=50, null=True, unique=True),
        ),
    ]
