# Generated by Django 5.0.6 on 2024-10-25 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_alter_userform_classe_alter_userform_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='role',
        ),
    ]
