# Generated by Django 5.0.6 on 2024-10-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_remove_userform_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur'), ('Directeur', 'Directeur'), ('Professeur', 'Professeur')], default='', max_length=50),
        ),
    ]
