# Generated by Django 5.0.6 on 2024-10-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_userform_matieres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecoles', models.CharField(choices=[('lycee bamban', 'lycee bamban'), ('lune de sam', 'Lune de sam'), ('GLC kenende', 'GLC kenende')], default='', max_length=50)),
            ],
        ),
    ]
