# Generated by Django 5.0.6 on 2024-10-26 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_ecole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('7eme', '7eme'), ('8eme', '8eme'), ('9eme', '9eme'), ('10eme', '10eme'), ('11emesm', '11eme SM'), ('11emese', '11eme SE'), ('11emess', '11eme SS'), ('12emesm', '12eme SM'), ('12emese', '12eme SE'), ('12emess', '12eme SS'), ('tsm', 'TSM'), ('tse', 'TSE'), ('tss', 'TSS')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matieres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matieres', models.CharField(choices=[('maths', 'Maths'), ('physique', 'physique'), ('chimie', 'Chimie')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Administrateur', 'Administrateur'), ('Directeur', 'Directeur'), ('Professeur', 'Professeur')], default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='ecole',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.ecole'),
        ),
        migrations.AddField(
            model_name='userform',
            name='ecole',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testapp.ecole'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='cours',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='ecoles',
            field=models.CharField(choices=[('lycee bamban', 'lycee bamban'), ('lune de sam', 'Lune de sam'), ('GLC kenende', 'GLC kenende')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.classes'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.classes'),
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateField(auto_now=True)),
                ('fichier', models.FileField(upload_to='pdf')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.classes')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.ecole')),
                ('matieres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.matieres')),
            ],
        ),
        migrations.AlterField(
            model_name='cours',
            name='matieres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.matieres'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='matieres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.matieres'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.role'),
        ),
    ]
