# Generated by Django 5.0.6 on 2024-10-26 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_classes_matieres_role_cours_ecole_userform_ecole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.role'),
        ),
    ]
