# Generated by Django 5.0.6 on 2024-10-26 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_alter_userform_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.classes'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='matieres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.matieres'),
        ),
    ]
