# Generated by Django 5.0.6 on 2024-10-26 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0022_alter_userform_classe_alter_userform_matieres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='ecole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.ecole'),
        ),
    ]
