# Generated by Django 5.0.6 on 2024-10-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_alter_userform_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='classe',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='ecoles',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matieres',
            name='matieres',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
