# Generated by Django 5.0.6 on 2024-10-26 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0025_alter_matieres_matieres_alter_role_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='matieres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.matieres'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.role'),
        ),
    ]
