# Generated by Django 5.0.6 on 2024-10-26 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_alter_role_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.role'),
        ),
    ]
