# Generated by Django 5.0.6 on 2024-10-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0028_alter_userform_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
    ]
