# Generated by Django 5.0.6 on 2024-10-26 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0031_alter_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.role'),
        ),
    ]
