# Generated by Django 5.0.6 on 2024-10-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0032_role_date_alter_userform_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='date',
            new_name='date_ajout',
        ),
    ]
