# Generated by Django 5.0.6 on 2024-10-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0033_rename_date_role_date_ajout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='role',
        ),
        migrations.AlterField(
            model_name='userform',
            name='classe',
            field=models.CharField(choices=[('7eme', '7eme'), ('8eme', '8eme'), ('9eme', '9eme'), ('10eme', '10eme'), ('11emesm', '11eme SM'), ('11emese', '11eme SE'), ('11emess', '11eme SS'), ('12emesm', '12eme SM'), ('12emese', '12eme SE'), ('12emess', '12eme SS'), ('tsm', 'TSM'), ('tse', 'TSE'), ('tss', 'TSS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='matieres',
            field=models.CharField(choices=[('maths', 'maths'), ('physique', 'physique'), ('chimie', 'chimie'), ('philo', 'philo'), ('français', 'français'), ('histoire', 'histoire'), ('biologie', 'biologie'), ('anglais', 'anglais'), ('geographie', 'geographie'), ('ecm', 'ecm')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
