# Generated by Django 5.0.6 on 2024-10-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0034_remove_userform_role_alter_userform_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='matieres',
            field=models.CharField(choices=[('maths', 'maths'), ('physique', 'physique'), ('chimie', 'chimie'), ('philo', 'philo'), ('français', 'français'), ('histoire', 'histoire'), ('biologie', 'biologie'), ('anglais', 'anglais'), ('geographie', 'geographie'), ('ecm', 'ecm')], default='', max_length=50),
        ),
    ]
