# Generated by Django 5.0.6 on 2024-10-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0035_alter_userform_matieres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='matieres',
            field=models.CharField(choices=[('maths', 'maths'), ('physique', 'physique'), ('chimie', 'chimie'), ('philo', 'philo'), ('français', 'français'), ('histoire', 'histoire'), ('biologie', 'biologie'), ('anglais', 'anglais'), ('geographie', 'geographie'), ('ecm', 'ecm')], default=None, max_length=50, null=True),
        ),
    ]
