# Generated by Django 5.0.6 on 2024-10-27 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0037_alter_userform_matieres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.ecole'),
        ),
    ]
