# Generated by Django 5.0.6 on 2024-10-27 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0038_alter_userform_ecole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, null=True)),
                ('date_ajout', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userform',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.classes'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='matieres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.matieres'),
        ),
        migrations.AddField(
            model_name='userform',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.role'),
        ),
    ]
