# Generated by Django 5.0.6 on 2024-10-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0039_role_alter_userform_classe_alter_userform_matieres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
