# Generated by Django 5.0.6 on 2024-10-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0040_remove_userform_role_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='date_aj',
            field=models.DateField(auto_now=True),
        ),
    ]
