# Generated by Django 5.0.6 on 2024-10-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0041_devoir_date_aj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoir',
            name='date_aj',
        ),
        migrations.AlterField(
            model_name='userform',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
