# Generated by Django 5.0.6 on 2024-10-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0043_devoir_image_alter_devoir_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='devoir'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='image',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to='devoir'),
        ),
    ]
