# Generated by Django 5.0.6 on 2024-10-31 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0046_devoir_num_devoir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoir',
            name='num_devoir',
        ),
        migrations.CreateModel(
            name='Traiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_devoir', models.CharField(blank=True, max_length=50, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.classes')),
                ('matieres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.matieres')),
            ],
        ),
    ]
