# Generated by Django 5.0.6 on 2024-10-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0048_traiter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='num_devoir',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
