# Generated by Django 5.0.6 on 2024-10-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0049_devoir_num_devoir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='num_devoir',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
