# Generated by Django 5.0.6 on 2024-10-31 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0050_alter_devoir_num_devoir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devoir',
            old_name='image',
            new_name='traiter',
        ),
        migrations.DeleteModel(
            name='Traiter',
        ),
    ]
