# Generated by Django 5.0.6 on 2024-10-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0051_rename_image_devoir_traiter_delete_traiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='note',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
