# Generated by Django 5.0.6 on 2024-10-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0052_devoir_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='statut',
            field=models.CharField(blank=True, choices=[('traiter', 'traiter'), ('enoncer', 'enoncer')], max_length=50, null=True),
        ),
    ]
