# Generated by Django 5.0.6 on 2024-10-31 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0053_devoir_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoir',
            name='note',
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='traiter',
        ),
        migrations.CreateModel(
            name='Traiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traiter', models.ImageField(blank=True, null=True, upload_to='devoir')),
                ('num_devoir', models.CharField(blank=True, max_length=50)),
                ('note', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, choices=[('traiter', 'traiter'), ('enoncer', 'enoncer')], max_length=50, null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.classes')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.ecole')),
                ('matieres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.matieres')),
            ],
        ),
    ]
