# Generated by Django 5.0.6 on 2024-10-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0054_remove_devoir_note_remove_devoir_traiter_traiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='image_sujet',
            field=models.ImageField(blank=True, null=True, upload_to='devoir'),
        ),
    ]
