# Generated by Django 5.0.6 on 2024-11-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0055_devoir_image_sujet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traiter',
            name='statut',
            field=models.CharField(blank=True, choices=[('traiter', 'traiter'), ('enoncer', 'enoncer'), ('noter', 'noter')], max_length=50, null=True),
        ),
    ]
