# Generated by Django 5.0.6 on 2024-11-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0056_alter_traiter_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='traiter',
            name='date_ajout',
            field=models.DateField(auto_now=True),
        ),
    ]
