# Generated by Django 5.0.6 on 2024-11-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0057_traiter_date_ajout'),
    ]

    operations = [
        migrations.AddField(
            model_name='traiter',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
